package com.multiarielle.skiscratcher.Ldtk;

import com.fasterxml.jackson.annotation.*;

@lombok.Data
public class LayerDefinition {
    @lombok.Getter(onMethod_ = {@JsonProperty("__type")})
    @lombok.Setter(onMethod_ = {@JsonProperty("__type")})
    private String type;
    @lombok.Getter(onMethod_ = {@JsonProperty("autoRuleGroups")})
    @lombok.Setter(onMethod_ = {@JsonProperty("autoRuleGroups")})
    private AutoLayerRuleGroup[] autoRuleGroups;
    @lombok.Getter(onMethod_ = {@JsonProperty("autoSourceLayerDefUid")})
    @lombok.Setter(onMethod_ = {@JsonProperty("autoSourceLayerDefUid")})
    private Long autoSourceLayerDefUid;
    @lombok.Getter(onMethod_ = {@JsonProperty("autoTilesetDefUid")})
    @lombok.Setter(onMethod_ = {@JsonProperty("autoTilesetDefUid")})
    private Long autoTilesetDefUid;
    @lombok.Getter(onMethod_ = {@JsonProperty("displayOpacity")})
    @lombok.Setter(onMethod_ = {@JsonProperty("displayOpacity")})
    private double displayOpacity;
    @lombok.Getter(onMethod_ = {@JsonProperty("excludedTags")})
    @lombok.Setter(onMethod_ = {@JsonProperty("excludedTags")})
    private String[] excludedTags;
    @lombok.Getter(onMethod_ = {@JsonProperty("gridSize")})
    @lombok.Setter(onMethod_ = {@JsonProperty("gridSize")})
    private long gridSize;
    @lombok.Getter(onMethod_ = {@JsonProperty("guideGridHei")})
    @lombok.Setter(onMethod_ = {@JsonProperty("guideGridHei")})
    private long guideGridHei;
    @lombok.Getter(onMethod_ = {@JsonProperty("guideGridWid")})
    @lombok.Setter(onMethod_ = {@JsonProperty("guideGridWid")})
    private long guideGridWid;
    @lombok.Getter(onMethod_ = {@JsonProperty("hideFieldsWhenInactive")})
    @lombok.Setter(onMethod_ = {@JsonProperty("hideFieldsWhenInactive")})
    private boolean hideFieldsWhenInactive;
    @lombok.Getter(onMethod_ = {@JsonProperty("hideInList")})
    @lombok.Setter(onMethod_ = {@JsonProperty("hideInList")})
    private boolean hideInList;
    @lombok.Getter(onMethod_ = {@JsonProperty("identifier")})
    @lombok.Setter(onMethod_ = {@JsonProperty("identifier")})
    private String identifier;
    @lombok.Getter(onMethod_ = {@JsonProperty("inactiveOpacity")})
    @lombok.Setter(onMethod_ = {@JsonProperty("inactiveOpacity")})
    private double inactiveOpacity;
    @lombok.Getter(onMethod_ = {@JsonProperty("intGridValues")})
    @lombok.Setter(onMethod_ = {@JsonProperty("intGridValues")})
    private IntGridValueDefinition[] intGridValues;
    @lombok.Getter(onMethod_ = {@JsonProperty("parallaxFactorX")})
    @lombok.Setter(onMethod_ = {@JsonProperty("parallaxFactorX")})
    private double parallaxFactorX;
    @lombok.Getter(onMethod_ = {@JsonProperty("parallaxFactorY")})
    @lombok.Setter(onMethod_ = {@JsonProperty("parallaxFactorY")})
    private double parallaxFactorY;
    @lombok.Getter(onMethod_ = {@JsonProperty("parallaxScaling")})
    @lombok.Setter(onMethod_ = {@JsonProperty("parallaxScaling")})
    private boolean parallaxScaling;
    @lombok.Getter(onMethod_ = {@JsonProperty("pxOffsetX")})
    @lombok.Setter(onMethod_ = {@JsonProperty("pxOffsetX")})
    private long pxOffsetX;
    @lombok.Getter(onMethod_ = {@JsonProperty("pxOffsetY")})
    @lombok.Setter(onMethod_ = {@JsonProperty("pxOffsetY")})
    private long pxOffsetY;
    @lombok.Getter(onMethod_ = {@JsonProperty("requiredTags")})
    @lombok.Setter(onMethod_ = {@JsonProperty("requiredTags")})
    private String[] requiredTags;
    @lombok.Getter(onMethod_ = {@JsonProperty("tilePivotX")})
    @lombok.Setter(onMethod_ = {@JsonProperty("tilePivotX")})
    private double tilePivotX;
    @lombok.Getter(onMethod_ = {@JsonProperty("tilePivotY")})
    @lombok.Setter(onMethod_ = {@JsonProperty("tilePivotY")})
    private double tilePivotY;
    @lombok.Getter(onMethod_ = {@JsonProperty("tilesetDefUid")})
    @lombok.Setter(onMethod_ = {@JsonProperty("tilesetDefUid")})
    private Long tilesetDefUid;
    @lombok.Getter(onMethod_ = {@JsonProperty("type")})
    @lombok.Setter(onMethod_ = {@JsonProperty("type")})
    private Type layerDefinitionType;
    @lombok.Getter(onMethod_ = {@JsonProperty("uid")})
    @lombok.Setter(onMethod_ = {@JsonProperty("uid")})
    private long uid;
}
